sudo: required
dist: trusty
os: linux
language: generic

env:
  - EMULATOR_VERSION=22 
  - TARGET_VERSION=28 
  #- ABI="google_apis;armeabi-v7a" 
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3 
  - ADB_INSTALL_TIMEOUT=20 
  - QEMU_AUDIO_DRV=none

  - SYS=25 ABI="google_apis;arm64-v8a"
  - SYS=25 ABI="google_apis;armeabi-v7a"
  - SYS=24 ABI="google_apis;arm64-v8a"
  - SYS=24 ABI="google_apis;armeabi-v7a"
  - SYS=23 ABI="google_apis;armeabi-v7a"

  - SYS=22 ABI="default;x86" # demo failure due to no accelerator on travis
  - SYS=22 ABI="default;x86_64" # demo failure due to no accelerator on travis
  - SYS=22 ABI="google_apis;armeabi-v7a"
  - SYS=22 ABI="google_apis;x86" # demo failure due to no accelerator on travis
  - SYS=22 ABI="google_apis;x86_64" # demo failure due to no accelerator on travis
  - SYS=22 ABI="default;armeabi-v7a"

  - SYS=21 ABI="default;armeabi-v7a"
  - SYS=20 ABI="default;armeabi-v7a"
  - SYS=19 ABI="default;armeabi-v7a"
  - SYS=18 ABI="default;armeabi-v7a"
  - SYS=17 ABI="default;armeabi-v7a"
  - SYS=16 ABI="default;armeabi-v7a"
  - SYS=15 ABI="default;armeabi-v7a"
  - SYS=14 ABI="default;armeabi-v7a"
  - SYS=10 ABI="default;armeabi-v7a"

before_install:
  # Install the Android SDK dependency
  - export ANDROID_HOME=~/android-sdk-linux
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  - HOMEBREW_NO_AUTO_UPDATE=1
  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses
  # Platform tools
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -15
  # install older packages (for emulator)
  - sdkmanager "build-tools;25.0.2" "platforms;android-25" > /dev/null
  # Create and start emulator.
  - sdkmanager "system-images;android-$SYS;$ABI" > /dev/null
  - sdkmanager --list | head -15
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$SYS;$ABI"
  # use the absolute emulator path in case older version installed (on default path)
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader &

  before_script:
  # Wait for emulator to startup.
  - ./scripts/android-wait-for-emulator.sh
  - adb shell input keyevent 82

  script:
  - echo "Done."