language: android

env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=22
 - ANDROID_BUILD_TOOLS=26.0.2
 - ADB_INSTALL_TIMEOUT=20 # minutes
 - ANDROID_ABI=google_apis/armeabi-v7a
 - QEMU_AUDIO_DRV=none # Remove audio

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_API
    - android-$EMULATOR_API

    - extra-android-support

    # The API level used by the emulator
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API

# before_install:
#   - yes | sdkmanager "platforms;android-26"

before_script: 
  - echo no | android create avd --force -n test -t android-$EMULATOR_API --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

  # script:
  #   - ./gradlew assembleDebug
